### ISSUE TITLE
Binary files in git

### ISSUE THREAD

**Issue by hhirsch** [goblinhack/gorynlich#10]
You want to get all the binary files out of your source repository and put them into submodules. This way people do not have to download the entire history of the binary files and their checkout is much faster.

**Comment by goblinhack** [comment]
Thanks - removed the DS_Store files - had no idea they were there

neil

**Comment by hhirsch** [comment]
Just put this to the test and as I suspected. The cloning process is very awkward. I intend to fix this.

**Comment by goblinhack** [comment]
Thanks for offering to help

neil

**Comment by hhirsch** [comment]
Ok. I started https://github.com/hhirsch/gorynlich-third-party and https://github.com/hhirsch/gorynlich-data I will tranfer the repositories to you once I am done. I forgot to create a repo for the xcode dir though. Is it important or will xcode create it automatically anyhow?

**Comment by goblinhack** [comment]
It needs to be there for xcode

neil

**Comment by hhirsch** [comment]
It has a directory with all the assets again. Can you just put it in a seperate repo and people can check it out if they need it?

**Comment by goblinhack** [comment]
No that's getting too messy - it's needed to build the target for macos

The assets should only be icons and the like - i.e. it should not be massive

I had a look - it's 7Mb - but there were some large image files in there I
copied over - so now only 2mb

neil

**Comment by hhirsch** [comment]
Sorry. Just realized that the whole thing is not even an issue for you and that I wasted 2 hours.

**Comment by goblinhack** [comment]
Well the guy that didn't like the one large repo - I ran
https://rtyley.github.io/bfg-repo-cleaner/
to clean it up - and it all seems much smaller

but removing the xcode files has helped too

thanks
