### ISSUE TITLE
License of code and art assets?

### ISSUE THREAD

**Issue by poVoq** [goblinhack/gorynlich#2]
No license information to be found... thanks for adding.

**Comment by goblinhack** [comment]
hi added,

 Copyright (C) 2014-2015 Neil McGill

 This game is free software; you can redistribute it and/or
 modify it under the terms of the GNU Library General Public
 License as published by the Free Software Foundation; either
 version 2 of the License, or (at your option) any later version.

 This game is distributed in the hope that it will be fun,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Library General Public License for more details.

 You should have received a copy of the GNU Library General Public
 License along with this game; if not, write to the Free
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 goblinhack@gmail.com

 Art is used with permission from

    Charlotte McGill,
    neoguid@hotmail.com

 Music is used with permission from

    Deceased Senior Technician (nosoapradio.us)

neil

**Comment by poVoq** [comment]
ok, so all the art and music is only freeware and the code in LGPLv2. Good to know ;)
