### ISSUE TITLE
Libre graphics update?

### ISSUE THREAD

**Issue by poVoq** [goblinhack/gorynlich#3]
Given the high amount of (relatively good) programmer's art in this game, it might be nice to give it a bit of an update for a more consistent style?

Btw: are sprite normal-maps supported?

I looked a bit around on OpenGameArt.org, for what could be a good base character set, and the nice CC-by-SA assets from the Wrmysun: http://opengameart.org/users/andrettin seem a perfect fit given all the dwarves ;)

Alternatively this might also be a good start: http://opengameart.org/content/unfinished-dungeon-tileset & http://opengameart.org/content/dungeon-tileset

Or this: http://opengameart.org/content/a-blocky-dungeon

The artist Buch has in general a lot of nice stuff that could be useful for GUI etc graphics:
http://opengameart.org/users/buch

For items this comes to mind: http://opengameart.org/content/recolor-all-the-items

But this set is also great (less pixelish): http://opengameart.org/content/golden-items-rip-upgrade-pack & http://opengameart.org/content/fantasy-icon-pack-by-ravenmore-0

Alternatively the rich LPC set (very RPG focussed) could also be utilized? See for example: http://opengameart.org/content/lpc-dungeon-elements

Some more nice tilesets:
http://opengameart.org/content/cave-tileset-0
http://opengameart.org/content/sewer-tileset

Here I collected a lot of good music and sound effects for a defunct project a while ago:
http://opengameart.org/content/music-and-soundfx-for-a-3d-action-rpg
(for SFX this one stands out: http://opengameart.org/content/rpg-sound-pack )

Anyways... plenty more great assets on OGA... so no excuse for the programmer's art ;)

**Comment by goblinhack** [comment]
Dude, I'm crushed, programmers art ;) I kinda like the pixel-ish art 8)
originally all sprites were
16x16 but I wanted a bit more detail so doubled them up.

I was initially thinking too I could try and one day get it onto steam and
so wanted to use my own limited art stuff - but frankly I prefer to just
give it away. Less hassle and better karma. And like you point out now,
more scope for pulling in other graphics - as it's just too much for one
person to do and much tho I'd to be, I'm not that good an artist.

Lots of nice links, thanks. I'll definitely have a look - I actually just
reached out to one nice person
on deviant art and added 64 different types of fungi

But I still like the slightly crap style 8) I wouldn't want it to look all
smooth and professional even
if I was able to do that 8)

tx

neil
