### ISSUE TITLE
CRASHY MC CRASHERSON

### ISSUE THREAD

**Issue by donaldsharp** [goblinhack/gorynlich#4]
00:01:28.044: ERROR: FATAL ERROR: Failed assert
*** Error in `/home/sharpd/gorynlich/gorynlich': free(): invalid pointer: 0x00000000254e62a0 ***

Program received signal SIGABRT, Aborted.
0x00007ffff6baacc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6baacc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6bae0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6be7394 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffff6cf5b28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6bf366e in malloc_printerr (ptr=<optimized out>, str=0x7ffff6cf1c19 "free(): invalid pointer", action=1)
    at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x0000000013382136 in tree_empty (root=0x1c102d10, func=0x0) at tree.c:1246
#6  0x0000000013382184 in tree_destroy (rootp=0x18d223b0 <wid_top_level4>, func=0x0) at tree.c:1264
#7  0x0000000013394f1a in wid_fini () at wid.c:176
#8  0x000000001330c815 in quit () at main.c:154
#9  0x000000001330cade in quit () at main.c:240
#10 die () at main.c:235
#11 0x000000001330bb8c in croak_ (fmt=0x1340a732 "Failed assert", args=args@entry=0x7fffffffd618) at log.c:366
#12 0x000000001330bc2c in CROAK (fmt=<optimized out>) at log.c:414
#13 0x0000000013380a2a in sibling (node=0x254e62a0) at tree.c:65
#14 0x0000000013380aff in uncle (node=0x1cddc7a0) at tree.c:79
#15 0x00000000133815a7 in tree_balance (root=0x1c102d10, node=0x1cddc7a0) at tree.c:891
#16 0x0000000013381822 in tree_insert (root=0x1c102d10, node=0x1cddc7a0) at tree.c:981
#17 0x0000000013384acf in wid_tree4_wids_being_destroyed_insert (w=0x1cddc700) at wid.c:2870
#18 0x00000000133b9e3d in wid_intro_menu_create () at wid_intro.c:190
#19 wid_intro_visible () at wid_intro.c:156
#20 0x000000001339373f in wid_destroy_delay (wp=0x5cee, wp@entry=0x18d22750 <wid_intro_story1>, delay=0) at wid.c:3243
#21 0x0000000013393937 in wid_destroy_nodelay (wp=wp@entry=0x18d22750 <wid_intro_story1>) at wid.c:3260
#22 0x00000000133bac52 in wid_intro_story_destroy () at wid_intro_demo.c:409
#23 0x00000000133bb5d9 in wid_intro_story6_destroy_done (w=<optimized out>) at wid_intro_demo.c:50
#24 0x000000001339373f in wid_destroy_delay (wp=0x5cee, delay=2000) at wid.c:3243
#25 0x0000000013394d7d in wid_destroy (wp=<optimized out>) at wid.c:3255
#26 wid_gc (w=0x0) at wid.c:7629
#27 wid_gc_all () at wid.c:9751
#28 0x000000001332eca8 in sdl_loop () at sdl.c:1436
#29 0x0000000000449a57 in main (argc=<optimized out>, argv=<optimized out>) at main.c:860
(gdb) 00:01:28.044: ERROR: FATAL ERROR: Failed assert
Undefined command: "00".  Try "help".
(gdb) *** Error in `/home/sharpd/gorynlich/gorynlich': free(): invalid pointer: 0x00000000254e62a0 ***
Undefined command: "".  Try "help".
(gdb) 
Undefined command: "".  Try "help".
(gdb) Program received signal SIGABRT, Aborted.
Undefined command: "Program".  Try "help".
(gdb) 0x00007ffff6baacc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
Undefined command: "0x00007ffff6baacc9".  Try "help".
(gdb) 56../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
Undefined command: "56".  Try "help".
(gdb) (gdb) bt
Undefined command: "".  Try "help".
(gdb) #0  0x00007ffff6baacc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
(gdb) #1  0x00007ffff6bae0d8 in __GI_abort () at abort.c:89
(gdb) #2  0x00007ffff6be7394 in __libc_message (do_abort=do_abort@entry=1, 
(gdb)     fmt=fmt@entry=0x7ffff6cf5b28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
Undefined command: "fmt".  Try "help".
(gdb) #3  0x00007ffff6bf366e in malloc_printerr (ptr=<optimized out>, str=0x7ffff6cf1c19 "free(): invalid pointer", action=1)
(gdb)     at malloc.c:4996

But, Wait!  It gets better! 

(gdb) f 15
#15 0x00000000133815a7 in tree_balance (root=0x1c102d10, node=0x1cddc7a0) at tree.c:891
891	    if (tree_node_color(uncle(node)) == RB_RED) {
(gdb) p *node
$1 = {right = 0x0, left = 0x0, parent = 0x0, color = 1, is_static_mem = 0}
(gdb) p *tree
No symbol "tree" in current context.
(gdb) p *root
$2 = {compare_func = 0x0, node = 0x1cddc7a0, size = 4294967295, offset = 160, type = TREE_KEY_INTEGER}
(gdb) 

You may ask yourself, WTF mate? how did I get here?  node->parent is NULL! 

And if you are wondering how to actually reproduce!  You'll have to come to beer-n-cookies on friday!  3:30 pm.  We probably will be all out of cookies but we do have beer.

Ping me if you want the address.

**Comment by goblinhack** [comment]
Donlad, fixed, I believe. I saw this one time before and dismissed it as
alpha radiation 8)

don't you love red black trees - never writing one of those again!

tx for trying it . I'll ping you offline for other stuff

neil
